services:
  lab2-safe:
    build: .
    ports:
      - "8083:8083"
    environment:
      - DELAY_SEC=1.0
      - RATE_LIMIT=5
  lab2-naive:
    build: .
    command: ["python", "server_threaded_naive.py"]
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - DELAY_SEC=1.0
      - RATE_LIMIT=5
